<?php

/**
 * BaseForumtopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $forumcategory_id
 * @property string $title
 * @property integer $published
 * @property Forumcategory $Forumcategory
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method integer       getForumcategoryId()  Returns the current record's "forumcategory_id" value
 * @method string        getTitle()            Returns the current record's "title" value
 * @method integer       getPublished()        Returns the current record's "published" value
 * @method Forumcategory getForumcategory()    Returns the current record's "Forumcategory" value
 * @method Forumtopic    setId()               Sets the current record's "id" value
 * @method Forumtopic    setForumcategoryId()  Sets the current record's "forumcategory_id" value
 * @method Forumtopic    setTitle()            Sets the current record's "title" value
 * @method Forumtopic    setPublished()        Sets the current record's "published" value
 * @method Forumtopic    setForumcategory()    Sets the current record's "Forumcategory" value
 * 
 * @package    symfony-patches
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumtopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forumtopic');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('forumcategory_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'comment' => 'Category ID',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Topic name',
             'length' => 255,
             ));
        $this->hasColumn('published', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'comment' => 'Is topic published',
             'length' => 1,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('comment', 'Forum topics');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Forumcategory', array(
             'local' => 'forumcategory_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}