<?php

/**
 * ForumtopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumtopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumtopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Forumtopic');
    }
}