<?php

/**
 * ForumcategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumcategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumcategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Forumcategory');
    }
}